ASM nasm

SRC_DIR src
BUILD_DIR build

$(BUILD_DIR)/floppy.img: $(BUILD_DIR)/boot.bin
	cp $(BUILD_DIR)/boot.bin $(BUILD_DIR)/floppy.img
	trucate -s 1440k $(BUILD_DIR)/floppy.img

$(BUILD_DIR)/main.bin: $(SRC_DIR)/boot.asm
	$(ASM) $(SRC_DIR)/boot.asm -f bin -o $(BUILD_DIR)/boot.bin